"""add streak to users

Revision ID: 9d0a3d4f5c6b
Revises: e92976378f02
Create Date: 2024-03-21 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d0a3d4f5c6b'
down_revision = 'e92976378f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_streak', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('last_active_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_date')
    op.drop_column('users', 'current_streak')
    # ### end Alembic commands ###
